apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kurkutu-
commonLabels:
  app.kubernetes.io/instance: kurkutu

resources:
  - ../../base

# Build with:
#   kubectl kustomize --load-restrictor LoadRestrictionsNone deploy/k8s/overlays/kurkutu
configMapGenerator:
  - name: bot-config
    files:
      - bot.yaml=../../../../configs/kurkutu.yaml

secretGenerator:
  - name: bot-secrets
    envs:
      - secret.env

images:
  - name: ghcr.io/mrcupp/annoybots
    newTag: latest
