apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kurkutu-
commonLabels:
  app.kubernetes.io/instance: kurkutu

# Build with:
#   kubectl kustomize --load-restrictor LoadRestrictionsNone deploy/k8s/overlays/kurkutu
resources:
  - ../../base
  - secret.sops.yaml

configMapGenerator:
  - name: bot-config
    files:
      - bot.yaml=../../../../configs/kurkutu.yaml
  - name: bot-quotes
    options:
      disableNameSuffixHash: true
    files:
      - ../../../../data/quotes/classic.txt
      - ../../../../data/quotes/rickmorty.txt
      - ../../../../data/quotes/southpark.txt
      - ../../../../data/quotes/futurama.txt
      - ../../../../data/quotes/snuffbox.txt
      - ../../../../data/quotes/timeric.txt
      - ../../../../data/quotes/squidbillies.txt
      - ../../../../data/quotes/orgazmo.txt
  - name: bot-skits
    options:
      disableNameSuffixHash: true
    files:
      - skits.yaml=../../../../data/skits.yaml

images:
  - name: ghcr.io/mrcupp/annoybots
    newTag: latest # {"$imagepolicy": "flux-system:annoybots:tag"}
