# Kurkutu's secrets. Committed to Git ENCRYPTED.
#   1. Fill in real values.  2. sops --encrypt --in-place secret.sops.yaml
#   3. Commit. Flux decrypts at apply time (decryption.provider: sops).
apiVersion: v1
kind: Secret
metadata:
    name: bot-secrets
type: Opaque
stringData:
    KURKUTU_TESTNET_SASL: ENC[AES256_GCM,data:jpwdyFZaM4E=,iv:7THZgF9iWYq0XvUJQM2gZpIuaWntEtqoSzjIMY1/piY=,tag:fYQ+cQGSevREGyYViKtpEA==,type:str]
    KURKUTU_LIBERA_SASL: ENC[AES256_GCM,data:k/Ckx50Ry5I=,iv:BeNBc/uKDoOLzeV332vlphwe+u/7iY705U+Gl5NeGHI=,tag:PzImdSJlZvpO39mxxiptcA==,type:str]
    KURKUTU_TWITCH_TOKEN: ENC[AES256_GCM,data:vaorXIiS5Dk=,iv:u+ivocSKbsuNLS+5E51DNAxrcG0G4sJEVvUPITRAscQ=,tag:IZnS9UIVmjwniUTILsq7Ew==,type:str]
    KURKUTU_DISCORD_TOKEN: ENC[AES256_GCM,data:Qt3P5bzuUUM=,iv:ErA/hziIt6wCLy9TuWyGPaXtCMidRK/8OfRD0ue1mJE=,tag:Bvx6woNWg8ZyOcc8XkaDpg==,type:str]
    KURKUTU_ADMIN_PASSWORD: ENC[AES256_GCM,data:tSELpz2u2pA=,iv:ux5t4q1R7MezKeXObr6JOI3wQI3+bkZPEn83Xl3p7PU=,tag:1zpVYF8JsBkfO63l8UkC7A==,type:str]
    REDIS_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdVlVUUdjdi9PdkdWeTRN
            MmdTYzFNeDh1aXRiTkVhQ0pHNkhjcUg0dVU0CnVSZDU3Zi9mR2Fucll0OVZvMEFY
            WGdmaUpMZ3FuODl1WG5tR01PVG1PSkUKLS0tIGIrVlBhbDVGSUpzc2FSOG1zakp5
            M0JQTmtFd241cGxJamt0RWErTmRKVjAK1AMW0NjqoXIo/5RE7yH1ZnDDOI6iNCwO
            FUN5cQsRSfwFcTxInrY46jVi1ADRzmiLyx/lRH20Ccx1eVgmQPXtkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y5mjg49fm55fx0r5cs4je8p26zge2zmtmafgmr4hv3lrfrtldv8q4dycwa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T07:41:51Z"
    mac: ENC[AES256_GCM,data:kCUhGxvUgqQX9TnGlhhJ8I0sGp+AFvzt5qz2F1fCzVhNL5GwOvjl+/Q+vqpgN7W7Crzwt/RoV98pelYrCv6KBTVGk4Rs07T0Hk2e/UcpbGYfGsAHPjs5u57LGCsJkPpCvYME19ZjGxMAZMURMMq19ynsOMtN2dztIZkTZPphMig=,iv:/3/L0B2vQBOg9+jrhAOe20PacalX0/Mu5n1ANrx6Zto=,tag:qKOeeZrvbgDrNP6Xzux1uQ==,type:str]
    version: 3.13.1
