apiVersion: v1
kind: Service
metadata:
  name: annoybot
  labels:
    app.kubernetes.io/name: annoybot
spec:
  clusterIP: None  # headless: gives the StatefulSet pod a stable DNS name
  selector:
    app.kubernetes.io/name: annoybot
  ports:
    - name: http
      port: 8080
      targetPort: http
